[package]
name = "pg-completion-playground-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pg-completion = { path = "../../pg-completion" }
pg-parser = { path = "../../pg-parser" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
