use super::*;

#[test]
fn malformed_alter_table_commands_are_rejected_without_token_skipping() {
    assert_parse_errors(&[
        "alter table t add column",
        "alter table t add column c",
        "alter table t drop column",
        "alter table t alter column c",
        "alter table t alter column c set default",
        "alter table t alter column c set not",
        "alter table t alter column c set statistics nonsense",
        "alter table t alter column 0 set statistics 10",
        "alter table t alter column c reset ()",
        "alter table t validate constraint",
        "alter table t replica identity using index",
        "alter table t attach partition child",
        "alter table t detach partition child concurrently finalize",
        "alter table t split partition child into ()",
        "alter table t merge partitions () into child",
        "alter table t enable trigger",
        "alter table t set access method",
        "alter table t set tablespace",
        "alter table t set (fillfactor 80)",
        "alter table t reset (fillfactor 80)",
        "alter table t alter column c set (n_distinct 10)",
        "alter table t set logged garbage",
        "alter table t add column c int,",
        "alter table t add constraint",
        "alter table t add constraint c check ()",
        "alter table t alter constraint",
        "alter table t alter constraint c",
        "alter table t alter constraint c not valid",
        "alter table t alter column id add identity",
        "alter table t alter column id add generated as identity",
        "alter table t alter column id add generated always as identity ()",
        "alter table t alter column id set generated",
    ]);
}

#[test]
fn incomplete_alter_forms_are_rejected() {
    assert_parse_errors(&[
        "alter database select refresh collation version",
        "alter database app set tablespace select",
        "alter tablespace select set (seq_page_cost = 1)",
        "alter policy select on t using (true)",
        "alter event trigger select enable",
        "alter foreign data wrapper select no handler",
        "alter server select version '1'",
        "alter publication select set (publish = 'insert')",
        "alter subscription select enable",
        "alter table t rename column select to value",
        "alter table t drop column select",
        "alter table t enable trigger select",
        "alter table t set tablespace select",
        "alter table t replica identity using index select",
        "alter type app.composite rename attribute select to value",
        "alter table",
        "alter table if t owner to alice",
        "alter table t nonsense",
        "alter sequence",
        "alter sequence s nonsense",
        "alter database",
        "alter database d refresh version",
        "alter database d refresh collation",
        "alter database d refresh collation version garbage",
        "alter database d set tablespace",
        "alter system nonsense",
        "alter system set work_mem",
        "alter tablespace ts nonsense",
        "alter tablespace ts set ()",
        "alter role",
        "alter role all superuser",
        "alter group g user r",
        "alter type mood add value happy",
        "alter type mood rename value 'sad' 'happy'",
        "alter statistics st",
        "alter statistics st set statistics nonsense",
        "alter statistics st set statistics 1.5",
        "alter event trigger et",
        "alter event trigger et enable nonsense",
        "alter foreign data wrapper",
        "alter foreign data fdw options (host 'x')",
        "alter foreign data wrapper fdw nonsense",
        "alter foreign data wrapper fdw options (host db)",
        "alter server s",
        "alter server s version current_user",
        "alter subscription",
        "alter subscription s",
        "alter subscription s connection current_user",
        "alter subscription s set publication",
        "alter subscription s set publication p,",
        "alter subscription s add publication p,",
        "alter subscription s drop publication p,",
        "alter subscription s refresh nonsense",
        "alter subscription s set (enabled true)",
        "alter subscription s refresh sequences with (copy_data = true)",
        "alter subscription s enable with (copy_data = true)",
        "alter user mapping garbage",
        "alter user mapping for u server s",
        "alter user mapping for u server s options (host db)",
        "alter domain",
        "alter domain d set default",
        "alter domain d set nonsense",
        "alter domain d add check value > 0",
        "alter domain d drop constraint",
        "alter type t set ()",
        "alter type t set (input =)",
        "alter collation c refresh",
        "alter policy p t",
        "alter policy p on t using true",
        "alter policy p on t to using (true)",
        "alter property graph",
        "alter property graph g add nonsense",
        "alter property graph g drop vertex tables ()",
        "alter property graph g alter vertex table v add label l",
        "alter property graph g alter vertex table v alter label l add no properties",
        "alter property graph g alter vertex table v alter label l add properties all columns",
        "alter property graph g alter vertex table v alter label l add properties ()",
        "alter property graph g alter vertex table v alter label l add properties (id,)",
        "alter type composite add attribute c",
        "alter type composite drop attribute",
        "alter type composite alter attribute c type",
        "alter type composite alter attribute c set type int",
        "alter type composite add attribute c int not null",
        "alter type composite add attribute c int,",
        "alter extension",
        "alter extension e nonsense",
        "alter extension e update to",
        "alter extension e add function",
        "alter extension e add cast (int text)",
        "alter extension e add operator class opc btree",
        "alter extension e add policy p",
        "alter extension e add trigger t",
        "alter extension e add rule r",
        "alter operator family opf using btree",
        "alter operator family opf using btree add",
        "alter operator family opf using btree add operator 1 plus",
        "alter operator family opf using btree add operator 1 plus(int, int)",
        "alter operator family opf using btree drop operator 1 ()",
        "alter function f()",
        "alter function stable",
        "alter function f() security",
        "alter function f() cost",
        "alter function f() set work_mem",
        "alter operator +(int, int)",
        "alter operator +(int, int) set ()",
        "alter operator +(int, int) set (restrict app.f)",
        "alter operator +(int, int) set (restrict =)",
        "alter operator +(int, int) set (restrict = app.f garbage)",
        "alter text search dictionary",
        "alter text search dictionary d ()",
        "alter text search configuration c add mapping word with simple",
        "alter text search configuration c add mapping for with simple",
        "alter text search configuration c alter mapping replace simple",
        "alter text search configuration c drop mapping for",
        "alter table t rename to",
        "alter table t rename column to c",
        "alter domain d rename constraint c d2",
        "alter aggregate agg rename to agg2",
        "alter function if exists f() rename to g",
        "alter operator class opc rename to opc2",
        "alter function f() depends extension e",
        "alter function f() depends on extension",
        "alter table t depends on extension e",
        "alter index if exists i depends on extension e",
        "alter function f() set schema",
        "alter database d set schema s",
        "alter function if exists f() set schema s",
        "alter schema s owner role",
        "alter schema s owner to",
        "alter table t owner to",
        "alter extension e rename to e2",
        "alter access method heap rename to heap2",
        "alter operator +(int, int) rename to plus",
        "alter property graph if exists g rename to g2",
        "alter database app",
        "alter database app with",
        "alter system set work_mem = 1 + 2",
        "alter database d set local work_mem to '4MB'",
        "alter role r set session work_mem to '4MB'",
        "alter role r connection limit 1.5",
        "alter role r \"LOGIN\"",
        "alter default privileges for alice grant select on tables to bob",
        "alter default privileges for role user alice grant select on tables to bob",
        "alter default privileges",
        "alter default privileges garbage grant select on tables to bob",
        "alter default privileges in app grant select on tables to bob",
        "alter default privileges in schema app.audit grant select on tables to bob",
        "alter default privileges grant select on table t to bob",
        "alter default privileges grant select on databases to bob",
        "alter default privileges grant select on tables to bob granted by owner",
        "alter role 'alice' login",
        "alter type mood drop value 'sad'",
        "alter default privileges grant select, on tables to alice",
        "alter role alice rename to public",
        "alter table app.items alias rename to renamed_items",
        "alter foreign table app.items alias rename to renamed_items",
        "alter sequence only app.seq set schema archive",
        "alter extension if exists ext set schema archive",
        "alter schema if exists app owner to owner_role",
        "alter sequence s",
        "alter text search dictionary d (stopwords english)",
        "alter tablespace ts set (random_page_cost 1.1)",
    ]);
}
