use super::*;

#[test]
fn incomplete_drop_forms_are_rejected() {
    assert_parse_errors(&[
        "drop database select",
        "drop tablespace select",
        "drop subscription select",
        "drop nonsense",
        "drop table",
        "drop table if t",
        "drop foreign fdw",
        "drop foreign data fdw",
        "drop trigger tr",
        "drop rule r",
        "drop policy p",
        "drop schema app.other",
        "drop event ddl_event",
        "drop text search parser",
        "drop materialized mv",
        "drop database",
        "drop database app with",
        "drop database app ()",
        "drop database app with ()",
        "drop database app (force,)",
        "drop database app (verbose)",
        "drop database app force",
        "drop role",
        "drop cast garbage",
        "drop cast (int text)",
        "drop cast (int as)",
        "drop transform for int sql",
        "drop transform for language sql",
        "drop operator class opc btree",
        "drop operator family using btree",
        "drop tablespace",
        "drop tablespace ts cascade",
        "drop subscription",
        "drop subscription s garbage",
        "drop user mapping for u",
        "drop user mapping server s",
        "drop concurrently index i",
        "drop role 'alice'",
    ]);
}
