use super::*;

#[test]
fn incomplete_select_forms_are_rejected() {
    assert_parse_errors(&[
        "values",
        "values ()",
        "values (1,)",
        "values (1),",
        "table",
        "table only",
        "table only ()",
        "table public.items alias_name",
        "table public.items * alias_name",
        "select * from lateral public.items",
        "select * from lateral (items join other on true)",
        "select * from lateral graph_table(social match (person) columns (person.id as person_id))",
        "select * from (items)",
        "select * from (generate_series(1, 3))",
        "select * from generate_series(1, 3) tablesample system (10)",
        "select * from (select 1) as nested tablesample system (10)",
        "select * from items join other on true tablesample system (10)",
        "select * from items alias()",
        "select * from 'items'",
        "select * from catalog.schema.items.extra",
        "select select",
        "select value.1",
        "select value.'field'",
        "select 1 as 'answer'",
        "select 1 as 7",
        "select 1 as answer garbage",
        "select 1 +",
        "select @-@",
        "select operator() 1",
        "select custom_type(length => 1) 'x'",
        "select custom_type(1 order by 2) 'x'",
        "select f(all distinct x)",
        "select f(all variadic x)",
        "select f(distinct variadic x)",
        "select f(distinct x, variadic y)",
        "select 1 operator(pg_catalog.) 2",
        "select 1 operator(pg_catalog.+)",
        "select 1 = 2 = 3",
        "select value is null is null",
        "select value between 1 and 2 between 3 and 4",
        "select value like pattern ilike other_pattern",
        "select (1",
        "(select 1",
        "(update t set a = 1)",
        "select 1 union (update t set a = 1)",
        "select f(1",
        "select f(1,)",
        "select f(first =>)",
        "select f('first' => 1)",
        "select f(1 => 2)",
        "select f(distinct)",
        "select row(1,)",
        "select row(first => 1)",
        "select array[1,]",
        "select grouping()",
        "select xmlconcat()",
        "select xmlelement(name item, xmlattributes())",
        "select xmlforest()",
        "select ()",
        "select coalesce()",
        "select greatest()",
        "select nullif(1)",
        "select nullif(1, 2, 3)",
        "select 1 in ()",
        "select items[]",
        "select items[1",
        "select items[1:]]",
        "select items.",
        "select items.*.field",
        "select (row(a)).1",
        "select date 1",
        "select numeric(5, 2) 'x' 'y'",
        "select value::",
        "select value::numeric(,)",
        "select doc is json with",
        "select doc is json without keys",
        "select doc is json object with keys",
        "select ts at time",
        "select ts at nonsense",
        "select name similar 'a%'",
        "select name like 'a%' escape",
        "select name similar to 'a%' escape",
        "select name similar to any(array['a'])",
        "select name like any()",
        "select value is nonsense",
        "select value is not nonsense",
        "select value is nfc",
        "select current of item_cursor",
        "select f(variadic)",
        "select f(a order key)",
        "select f(distinct a) within group (order by a)",
        "select f(a order by b) within group (order by c)",
        "select f(a) filter (active)",
        "select f(a) ignore over win",
        "select f(a) over",
        "select f(a) over select",
        "select f(a) over (partition a)",
        "select json_objectagg(k value v) filter (active)",
        "select json_arrayagg(v) over",
        "select id = any",
        "select id = any()",
        "select id = all(delete from t)",
        "select exists(update t set value = 1)",
        "select array(1)",
        "select id = any(1, 2)",
        "select value overlaps (a, b)",
        "select row(a) overlaps row(b, c)",
        "select row(a, b) overlaps row(c)",
        "select array[[1, 2], 3]",
        "select array[[1, 2],]",
        "select cast(value)",
        "select cast(value as)",
        "select treat(value as)",
        "select extract(year ts)",
        "select extract(1 from ts)",
        "select extract(select from ts)",
        "select normalize(value, invalid)",
        "select position('a' text_value)",
        "select position(a and b in c)",
        "select position(a is null in c)",
        "select value between not lower_bound and upper_bound",
        "select overlay(text_value placing 'x' 2)",
        "select substring(text_value from)",
        "select substring(text_value similar pattern)",
        "select trim()",
        "select trim(both from)",
        "select xmlexists('/a' doc)",
        "select xmlexists('/a' passing by doc)",
        "select xmlexists('/' || 'a' passing doc)",
        "select xmlexists('/a' passing doc || other)",
        "select xmlexists(not true passing doc)",
        "select collation for value",
        "select distinct on a",
        "select distinct on () 1",
        "select distinct",
        "select distinct on (1)",
        "select distinct from items",
        "select distinct on (id) from items",
        "select 1 fetch first a + b rows only",
        "select 1 fetch next -a rows only",
        "select 1 offset a + b rows",
        "select 1 offset -a rows",
        "select json_object('a': 1 absent)",
        "select json_object('a': 1,)",
        "select json_array(1 null)",
        "select json_array(1,)",
        "select json_object('a': 1 with)",
        "select json_object('a': 1 without)",
        "select json_object('a': 1 with keys)",
        "select json_value(doc, '$' passing 1 as 123)",
        "select json_value(doc, '$' passing 1 as 'name')",
        "select json_query(doc, '$' with json_array wrapper)",
        "select json(doc format json encoding 'utf8')",
        "select json(doc format json encoding bogus)",
        "select * from json_table(doc format json encoding 'utf8', '$' columns (value int))",
        "select json_value(doc, '$' error on error null on empty)",
        "select * from json_table(doc, '$' columns (value int path '$' error on error null on empty))",
        "select * from json_table(doc, '$' columns (value int,))",
        "select json(doc without keys)",
        "select xmlforest(a,)",
        "select xmlelement(name 1)",
        "select xmlpi(name 'target')",
        "select xmlserialize(content doc as setof text)",
        "select xmlserialize(content doc as text[])",
        "select xmlforest(a as 1)",
        "select xmlelement(name x, xmlattributes(a,), b)",
        "select json_query(doc, '$' with)",
        "select json_query(doc, '$' with conditional array)",
        "select json_query(doc, '$' keep)",
        "select json_query(doc, '$' keep quotes on scalar)",
        "select json_query(doc, '$' null on error error on error)",
        "select json_query(doc, '$' empty on empty)",
        "select json_value(doc, '$' default 0 on empty null on empty)",
        "select * from json_table(doc, '$' columns (value int path '$' empty on empty))",
        "select json_query(doc, '$' passing value as value,)",
        "select 1 where",
        "select 1 into",
        "select 1 into local snapshot",
        "select 1 into global snapshot",
        "select 1 into temporary table",
        "select 1 between 0 2",
        "select 1 group nonsense",
        "select 1 group by all a",
        "select 1 group by rollup()",
        "select 1 group by cube(a,)",
        "select 1 group by grouping sets ()",
        "select 1 group by grouping sets (a,)",
        "select 1 order nonsense",
        "select 1 order by a using",
        "select 1 order by a nulls",
        "select 1 order by a asc desc",
        "select 1 order by a using operator()",
        "select 1 fetch 1 row only",
        "select 1 fetch first 1 only",
        "select 1 fetch first 1 row",
        "select 1 fetch first row with",
        "select 1 fetch first row ties",
        "select 1 limit 1 fetch first row only",
        "select 1 limit 1, 2",
        "select 1 limit 1 limit 2",
        "select 1 offset 1 offset 2",
        "select 1 fetch first row only limit 2",
        "select 1 fetch first row with ties",
        "select 1 order by 1 fetch first row with ties for update skip locked",
        "select (select 1; garbage)",
        "select * from",
        "select * from (items",
        "select * from items join customers",
        "select * from items cross join customers on true",
        "select * from items natural join customers using (id)",
        "select * from items join customers using ()",
        "select * from items tablesample system",
        "select * from items tablesample system ()",
        "select * from rows from ()",
        "select * from rows from (f(),)",
        "select * from rows from (1)",
        "select * from rows from (f() as ())",
        "select * from rows from (f()) with",
        "select * from f() as ()",
        "select * from f() as select",
        "select * from f() as named(select)",
        "select * from left_table join right_table using (id) as select",
        "select * from f() as typed(x int,)",
        "select * from xmltable(xmlnamespaces('/x' ns), '/x' passing doc columns (id int))",
        "select * from xmltable('/' || 'x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc || other columns id int)",
        "select * from xmltable('/x' passing by doc columns id int)",
        "select * from xmltable(not true passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(1 and 2 as n), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(not true as n), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(1 is null as n), '/x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc columns id int path 1 and 2)",
        "select * from xmltable('/x' passing doc columns id int path not true)",
        "select * from xmltable('/x' passing doc columns id int path 1 is null)",
        "select * from xmltable('/x' passing doc columns id int path 1 in (1, 2))",
        "select * from xmltable(xmlnamespaces(), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces('x' as ns,), '/x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc columns)",
        "select * from xmltable('/x' passing doc columns id int,)",
        "select * from xmltable('/x' passing doc columns id int default 1 and 2)",
        "select * from xmltable('/x' passing doc columns id int path 'x' path 'y')",
        "select * from xmltable('/x' passing doc columns id int default 1 default 2)",
        "select * from xmltable('/x' passing doc columns id int null not null)",
        "select * from xmltable('/x' passing doc columns id int foo 1)",
        "select * from xmltable('/x' passing doc columns id int __pg__is_not_null true)",
        "select * from xmltable('/x' passing doc columns 'id' int)",
        "select * from xmltable('/x' passing doc columns select int)",
        "select * from json_table(doc, '$' as select columns (id int))",
        "select * from json_table(doc, '$' columns (select int))",
        "select * from json_table(doc, '$' columns (nested path '$' as select columns (id int)))",
        "select * from items window",
        "select 1 window select as ()",
        "select * from items window w (partition by id)",
        "select * from items window w as (partition id)",
        "select * from items window w as (partition by)",
        "select * from items window w as (order by)",
        "select * from items window w as (rows unbounded following)",
        "select * from items window w as (rows between current row and 1 preceding)",
        "select * from items for nonsense",
        "select * from items for no update",
        "select * from items for update of",
        "select * from items for update skip",
        "select * from items for update for read only",
        "select * from items for share for read only",
        "select * from (update items set value = 1) changed",
        "select (insert into items values (1))",
        "select 1 in (delete from items)",
        "select json_array(update items set value = 1)",
        "select unique (select 1)",
        "select * from graph_table(g match (p is person |) columns (p.id))",
        "select * from graph_table(g match ((p)-(q) columns (p.id))",
        "select * from graph_table(g match (p){1,} columns (p.id))",
    ]);
}

#[test]
fn incomplete_with_and_dml_forms_are_rejected() {
    assert_parse_errors(&[
        "with x select 1",
        "with x as select 1",
        "with x() as (select 1) select * from x",
        "with x(id,) as (select 1) select * from x",
        "with x as (select 1), select * from x",
        "with x as (select 1) create table t (id int)",
        "with x as (create table t (id int)) select 1",
        "with select as (select 1) select 1",
        "with x(select) as (select 1) select 1",
        "with recursive x(id) as (values (1)) search first by id set ord select * from x",
        "with recursive x(id) as (values (1)) search depth by id set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by id, set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by id set select * from x",
        "with recursive x(id) as (values (1)) cycle set mark using path select * from x",
        "with recursive x(id) as (values (1)) cycle id, set mark using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark to 'Y' using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark default 'N' using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark using select * from x",
        "with outer_cte as (select 1) (with inner_cte as (select 2) select * from inner_cte)",
        "insert t values (1)",
        "insert into t",
        "insert into t alias values (1)",
        "insert into t as values (1)",
        "insert into t (payload.) values (1)",
        "insert into t (select) values (1)",
        "insert into t (nums[]) values (1)",
        "insert into t (id) default values",
        "insert into t overriding user value default values",
        "insert into t (id) overriding system value default values",
        "insert into t with x as (select 1) update source set id = 1",
        "insert into t with x as (select 1) delete from source",
        "insert into t with x as (select 1) merge into target using source on true when matched then do nothing",
        "insert into t values (1) on conflict () do nothing",
        "insert into t values (1) on conflict (id,) do nothing",
        "insert into t values (1) on conflict on constraint do nothing",
        "insert into t values (1) on conflict (id) where do nothing",
        "insert into t values (1) on conflict do update set",
        "insert into t values (1) returning",
        "insert into t values (1) returning with () id",
        "insert into t values (1) returning with (old as previous,) id",
        "insert into t values (1) returning with (old previous) id",
        "insert into t values (1) on conflict do select for",
        "insert into t values (1) on conflict do select for update of t",
        "insert into t values (1) on conflict do select skip locked",
        "insert into t values (1) on conflict do select where",
        "update t",
        "update t set",
        "update t alias(id) set id = 1",
        "update t set payload. = 1",
        "update t set select = 1",
        "update t set nums[] = 1",
        "update t set nums[1 = 1",
        "update t set (a., b) = row(1, 2)",
        "update t set id = 1 from",
        "update t set id = 1 where current of",
        "update t set id = 1 where current item_cursor",
        "update t for portion of valid_time set id = 1",
        "update t for portion of valid_time () set id = 1",
        "update t for portion of valid_time from start to set id = 1",
        "delete t",
        "delete from",
        "delete from t using",
        "delete from t where current of",
        "delete from t for portion of valid_time (requested_period",
        "merge into t using s on true",
        "merge into t using s on true when matched then insert values (1)",
        "merge into t using s on true when not matched by source then insert values (1)",
        "merge into t using s on true when not matched then update set id = 1",
        "merge into t using s on true when not matched by target then delete",
        "merge into t using s on true when matched then update set",
        "merge into t using s on true when not matched then insert values ()",
        "merge into t using s on true when not matched then insert (id) default values",
        "merge into t using s on true when not matched then insert overriding user value default values",
    ]);
}
