use super::*;

#[test]
fn malformed_comment_and_security_label_identities_are_rejected() {
    assert_parse_errors(&[
        "comment on table app. is 'x'",
        "comment on table select is 'x'",
        "comment on table app.* is 'x'",
        "comment on database app.db is 'x'",
        "comment on function f(int,) is 'x'",
        "comment on aggregate agg is 'x'",
        "comment on aggregate agg() is 'x'",
        "comment on operator + is 'x'",
        "comment on operator plus(int, int) is 'x'",
        "comment on cast int as text is 'x'",
        "comment on cast (int text) is 'x'",
        "comment on constraint c app.t is 'x'",
        "comment on constraint c on is 'x'",
        "comment on trigger tr app.t is 'x'",
        "comment on operator class app.ops is 'x'",
        "comment on operator class app.* using btree is 'x'",
        "comment on operator family app, ops using btree is 'x'",
        "comment on transform for app.t plpgsql is 'x'",
        "security label on function f(int,) is 'x'",
        "security label on operator +(int, int) is 'x'",
        "security label on constraint c on app.t is 'x'",
        "security label on policy p on app.t is 'x'",
        "security label on rule r on app.t is 'x'",
        "security label on trigger tr on app.t is 'x'",
        "security label on operator family app.ops using btree is 'x'",
        "security label on operator class app.ops using btree is 'x'",
        "security label on cast (int as text) is 'x'",
        "security label on transform for app.t language sql is 'x'",
        "security label for on table t is 'x'",
    ]);
}

#[test]
fn malformed_privilege_name_categories_are_rejected() {
    assert_parse_errors(&[
        "grant from on table items to alice",
        "grant select(select) on table items to alice",
        "grant select(app.id) on table items to alice",
        "grant all privileges (app.id) on table items to alice",
        "grant alter system(work_mem) on parameter work_mem to admin",
        "revoke select option for app_reader from alice",
    ]);
}

#[test]
fn top_level_statements_require_semicolon_separators() {
    let error = pg_parser::parse("checkpoint checkpoint")
        .expect_err("adjacent statements without a semicolon must be rejected");
    assert!(!error.message.is_empty());
}

#[test]
fn incomplete_utility_forms_are_rejected() {
    assert_parse_errors(&[
        "savepoint select",
        "prepare select as select 1",
        "execute select",
        "deallocate select",
        "listen select",
        "notify select",
        "unlisten select",
        "reindex schema select",
        "import foreign schema select from server s into local_schema",
        "import foreign schema remote from server select into local_schema",
        "declare select cursor for select 1",
        "set select to 'value'",
        "show",
        "show time",
        "show transaction isolation",
        "show work_mem garbage",
        "show app.",
        "start",
        "start transaction read",
        "start transaction read only,",
        "begin isolation nonsense",
        "begin read only,",
        "commit and",
        "rollback to",
        "savepoint",
        "release savepoint",
        "prepare transaction",
        "commit prepared gid",
        "rollback prepared gid",
        "prepare",
        "prepare p () as select 1",
        "prepare p (int,) as select 1",
        "prepare p (int) select 1",
        "prepare p as vacuum",
        "execute",
        "execute p()",
        "execute p(1,)",
        "execute p(1",
        "execute p garbage",
        "deallocate",
        "deallocate prepare",
        "deallocate all garbage",
        "explain",
        "explain vacuum t",
        "explain grant select on table t to alice",
        "explain checkpoint",
        "explain verbose analyze select 1",
        "explain () select 1",
        "explain call f()",
        "explain analyze analyze select 1",
        "explain verbose verbose select 1",
        "explain (analyze true) analyze select 1",
        "explain (analyze = true) select 1",
        "checkpoint (public.flush)",
        "vacuum (verbose true garbage) t",
        "vacuum (verbose = true) t",
        "vacuum app.items(app.id)",
        "analyze app.items(id,)",
        "analyze (select) t",
        "call",
        "call f",
        "call f(1) filter (where true)",
        "call f(1) over ()",
        "call f(1) within group (order by 1)",
        "call f(1) ignore nulls",
        "call f(1) respect nulls",
        "call f(1)::int",
        "do",
        "do language",
        "do select",
        "copy t nonsense",
        "copy t to stdout with ()",
        "copy t to stdout with (format = csv)",
        "copy t to stdout with (format app.csv)",
        "copy t to stdout with (reject_limit 1 + 2)",
        "copy t to stdout with (force_not_null ())",
        "copy t to stdout with (force_not_null (id, 2))",
        "copy t to stdout with (force_not_null (id,))",
        "copy t to stdout using '|'",
        "copy t to stdout delimiters",
        "copy (select 1) to stdout delimiters '|'",
        "copy t to stdout encoding as 'UTF8'",
        "copy t to stdout force quote",
        "copy t to stdout force not id",
        "copy (select 1) from stdout",
        "copy binary (select 1) to stdout",
        "set constraints deferred",
        "set constraints app.c, deferred",
        "set constraints app.c extra immediate",
        "set constraints all, app.c immediate",
        "set constraints app.c deferred immediate",
        "set app. to value",
        "reset app.",
        "do",
        "return value + 1",
        "copy (vacuum t) to stdout",
        "copy t to stdout where id > 0",
        "vacuum t (",
        "vacuum verbose full t",
        "vacuum full full t",
        "vacuum analyze verbose t",
        "vacuum t,",
        "analyze full t",
        "analyze freeze t",
        "analyze analyze t",
        "analyze t,",
        "checkpoint garbage",
        "discard garbage",
        "lock table",
        "lock table app.items alias",
        "lock table app.items,",
        "lock app.items in access mode",
        "lock app.items in row mode",
        "lock app.items in share update mode",
        "lock app.items in share row mode",
        "lock app.items in exclusive",
        "lock app.items in share exclusive mode",
        "lock app.items nowait in share mode",
        "lock only ()",
        "lock (app.items)",
        "lock app.items in share mode nowait garbage",
        "listen",
        "unlisten",
        "unlisten * garbage",
        "notify",
        "notify channel, 1",
        "notify channel,",
        "load extension.so",
        "load",
        "refresh materialized view",
        "refresh materialized concurrently view mv",
        "refresh materialized view mv concurrently",
        "refresh materialized view mv no data",
        "reindex nonsense",
        "reindex index",
        "reindex table",
        "reindex schema",
        "reindex schema app.extra",
        "reindex concurrently table app.items",
        "reindex table app.items concurrently",
        "reindex (verbose = true) table app.items",
        "reindex (public.verbose) table app.items",
        "reindex (verbose true garbage) table app.items",
        "reindex (select) table app.items",
        "truncate",
        "truncate table app.items alias",
        "truncate app.items,",
        "truncate app.items identity restart",
        "truncate app.items cascade restart identity",
        "repack using",
        "repack (verbose = true) app.items",
        "repack using index item_idx",
        "cluster using item_idx",
        "cluster (verbose true) verbose",
        "cluster (verbose true) verbose app.items",
        "cluster only app.items",
        "cluster app.items(id)",
        "cluster item_idx on",
        "reassign owned by old_owner",
        "comment on table items",
        "security label on table items is 1",
        "import foreign schema remote",
        "import foreign schema remote limit (items) from server srv into public",
        "import foreign schema remote limit to () from server srv into public",
        "import foreign schema remote limit to (items,) from server srv into public",
        "import foreign schema remote except to (items) from server srv into public",
        "import foreign schema remote limit to (items alias) from server srv into public",
        "import foreign schema remote from server srv into public options ()",
        "return",
        "wait for '0/0'",
        "wait for lsn 1",
        "wait for lsn '0/0' with ()",
        "wait for lsn '0/0' with (timeout 1,)",
        "wait for lsn '0/0' with (timeout = 1)",
        "set time zone 1 + 2",
        "set time zone interval '1' day",
        "set names UTF8",
        "set names 65001",
        "set catalog 'other_database'",
        "set role default",
        "set role 1",
        "set role select",
        "set session authorization 1",
        "set session authorization select",
        "set work_mem to 1 + 2",
        "begin work transaction",
        "begin read only,",
        "end transaction work",
        "commit work transaction",
        "rollback transaction work",
        "abort work transaction",
        "declare c cursor select 1",
        "declare c cursor for with x as (select 1) update source set id = 1",
        "declare c cursor for with x as (select 1) delete from source",
        "declare c cursor for with x as (select 1) merge into target using source on true when matched then do nothing",
        "close",
        "fetch",
        "fetch absolute from c",
        "fetch relative in c",
        "fetch forward + c",
        "fetch backward all 1 c",
        "fetch first 1 c",
        "move all",
        "grant select on table t to 'alice'",
        "grant role app_reader to alice",
        "revoke role app_reader from alice",
        "grant app_reader to group alice",
        "grant select on table t to alice cascade",
        "grant select on table t to alice restrict",
        "grant app_reader to alice cascade",
        "grant app_reader to alice restrict",
        "grant select, on table t to alice",
        "revoke select, on table t from alice",
        "grant app_reader, to alice",
        "grant all to alice",
        "grant all privileges to alice",
        "revoke all from alice",
        "grant usage on large objects 1 to alice",
        "grant usage on parameter app..work_mem to alice",
        "grant usage on table catalog.schema.table.extra to alice",
        "grant connect on database app.db to alice",
        "import foreign schema remote from server srv into public options (key 1)",
    ]);
}
