use super::common::parse_error;

#[test]
fn incomplete_select_forms_are_rejected() {
    for sql in [
        "values",
        "values ()",
        "values (1,)",
        "values (1),",
        "table",
        "table only",
        "table only ()",
        "table public.items alias_name",
        "table public.items * alias_name",
        "select * from lateral public.items",
        "select * from lateral (items join other on true)",
        "select * from lateral graph_table(social match (person) columns (person.id as person_id))",
        "select * from (items)",
        "select * from (generate_series(1, 3))",
        "select * from generate_series(1, 3) tablesample system (10)",
        "select * from (select 1) as nested tablesample system (10)",
        "select * from items join other on true tablesample system (10)",
        "select * from items alias()",
        "select * from 'items'",
        "select * from catalog.schema.items.extra",
        "select select",
        "select value.1",
        "select value.'field'",
        "select 1 as 'answer'",
        "select 1 as 7",
        "select 1 as answer garbage",
        "select 1 +",
        "select @-@",
        "select operator() 1",
        "select custom_type(length => 1) 'x'",
        "select custom_type(1 order by 2) 'x'",
        "select f(all distinct x)",
        "select f(all variadic x)",
        "select f(distinct variadic x)",
        "select f(distinct x, variadic y)",
        "select 1 operator(pg_catalog.) 2",
        "select 1 operator(pg_catalog.+)",
        "select 1 = 2 = 3",
        "select value between 1 and 2 between 3 and 4",
        "select value like pattern ilike other_pattern",
        "select (1",
        "(select 1",
        "(update t set a = 1)",
        "select 1 union (update t set a = 1)",
        "select f(1",
        "select f(1,)",
        "select f(first =>)",
        "select f('first' => 1)",
        "select f(1 => 2)",
        "select f(distinct)",
        "select row(1,)",
        "select row(first => 1)",
        "select array[1,]",
        "select grouping()",
        "select xmlconcat()",
        "select xmlelement(name item, xmlattributes())",
        "select xmlforest()",
        "select ()",
        "select coalesce()",
        "select greatest()",
        "select nullif(1)",
        "select nullif(1, 2, 3)",
        "select 1 in ()",
        "select items[]",
        "select items[1",
        "select items[1:]]",
        "select items.",
        "select items.*.field",
        "select (row(a)).1",
        "select date 1",
        "select numeric(5, 2) 'x' 'y'",
        "select value::",
        "select value::numeric(,)",
        "select doc is json with",
        "select doc is json without keys",
        "select doc is json object with keys",
        "select ts at time",
        "select ts at nonsense",
        "select name similar 'a%'",
        "select name like 'a%' escape",
        "select name similar to 'a%' escape",
        "select name similar to any(array['a'])",
        "select name like any()",
        "select value is nonsense",
        "select value is not nonsense",
        "select value is nfc",
        "select current of item_cursor",
        "select f(variadic)",
        "select f(a order key)",
        "select f(distinct a) within group (order by a)",
        "select f(a order by b) within group (order by c)",
        "select f(a) filter (active)",
        "select f(a) ignore over win",
        "select f(a) over",
        "select f(a) over select",
        "select f(a) over (partition a)",
        "select json_objectagg(k value v) filter (active)",
        "select json_arrayagg(v) over",
        "select id = any",
        "select id = any()",
        "select id = all(delete from t)",
        "select exists(update t set value = 1)",
        "select array(1)",
        "select id = any(1, 2)",
        "select value overlaps (a, b)",
        "select row(a) overlaps row(b, c)",
        "select row(a, b) overlaps row(c)",
        "select array[[1, 2], 3]",
        "select array[[1, 2],]",
        "select cast(value)",
        "select cast(value as)",
        "select treat(value as)",
        "select extract(year ts)",
        "select extract(1 from ts)",
        "select extract(select from ts)",
        "select normalize(value, invalid)",
        "select position('a' text_value)",
        "select position(a and b in c)",
        "select position(a is null in c)",
        "select value between not lower_bound and upper_bound",
        "select overlay(text_value placing 'x' 2)",
        "select substring(text_value from)",
        "select substring(text_value similar pattern)",
        "select trim()",
        "select trim(both from)",
        "select xmlexists('/a' doc)",
        "select xmlexists('/a' passing by doc)",
        "select xmlexists('/' || 'a' passing doc)",
        "select xmlexists('/a' passing doc || other)",
        "select xmlexists(not true passing doc)",
        "select collation for value",
        "select distinct on a",
        "select distinct on () 1",
        "select distinct",
        "select distinct on (1)",
        "select distinct from items",
        "select distinct on (id) from items",
        "select 1 fetch first a + b rows only",
        "select 1 fetch next -a rows only",
        "select 1 offset a + b rows",
        "select 1 offset -a rows",
        "select json_object('a': 1 absent)",
        "select json_object('a': 1,)",
        "select json_array(1 null)",
        "select json_array(1,)",
        "select json_object('a': 1 with)",
        "select json_object('a': 1 without)",
        "select json_object('a': 1 with keys)",
        "select json_value(doc, '$' passing 1 as 123)",
        "select json_value(doc, '$' passing 1 as 'name')",
        "select json_query(doc, '$' with json_array wrapper)",
        "select json(doc format json encoding 'utf8')",
        "select json(doc format json encoding bogus)",
        "select * from json_table(doc format json encoding 'utf8', '$' columns (value int))",
        "select json_value(doc, '$' error on error null on empty)",
        "select * from json_table(doc, '$' columns (value int path '$' error on error null on empty))",
        "select * from json_table(doc, '$' columns (value int,))",
        "select json(doc without keys)",
        "select xmlforest(a,)",
        "select xmlelement(name 1)",
        "select xmlpi(name 'target')",
        "select xmlserialize(content doc as setof text)",
        "select xmlserialize(content doc as text[])",
        "select xmlforest(a as 1)",
        "select xmlelement(name x, xmlattributes(a,), b)",
        "select json_query(doc, '$' with)",
        "select json_query(doc, '$' with conditional array)",
        "select json_query(doc, '$' keep)",
        "select json_query(doc, '$' keep quotes on scalar)",
        "select json_query(doc, '$' null on error error on error)",
        "select json_query(doc, '$' empty on empty)",
        "select json_value(doc, '$' default 0 on empty null on empty)",
        "select * from json_table(doc, '$' columns (value int path '$' empty on empty))",
        "select json_query(doc, '$' passing value as value,)",
        "select 1 where",
        "select 1 into",
        "select 1 into local snapshot",
        "select 1 into global snapshot",
        "select 1 into temporary table",
        "select 1 between 0 2",
        "select 1 group nonsense",
        "select 1 group by all",
        "select 1 group by rollup()",
        "select 1 group by cube(a,)",
        "select 1 group by grouping sets ()",
        "select 1 group by grouping sets (a,)",
        "select 1 order nonsense",
        "select 1 order by a using",
        "select 1 order by a nulls",
        "select 1 order by a asc desc",
        "select 1 order by a using operator()",
        "select 1 fetch 1 row only",
        "select 1 fetch first 1 only",
        "select 1 fetch first 1 row",
        "select 1 fetch first row with",
        "select 1 fetch first row ties",
        "select 1 limit 1 fetch first row only",
        "select 1 limit 1, 2",
        "select 1 limit 1 limit 2",
        "select 1 offset 1 offset 2",
        "select 1 fetch first row only limit 2",
        "select 1 fetch first row with ties",
        "select 1 order by 1 fetch first row with ties for update skip locked",
        "select (select 1; garbage)",
        "select * from",
        "select * from (items",
        "select * from items join customers",
        "select * from items cross join customers on true",
        "select * from items natural join customers using (id)",
        "select * from items join customers using ()",
        "select * from items tablesample system",
        "select * from items tablesample system ()",
        "select * from rows from ()",
        "select * from rows from (f(),)",
        "select * from rows from (1)",
        "select * from rows from (f() as ())",
        "select * from rows from (f()) with",
        "select * from f() as ()",
        "select * from f() as select",
        "select * from f() as named(select)",
        "select * from left_table join right_table using (id) as select",
        "select * from f() as typed(x int,)",
        "select * from xmltable(xmlnamespaces('/x' ns), '/x' passing doc columns (id int))",
        "select * from xmltable('/' || 'x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc || other columns id int)",
        "select * from xmltable('/x' passing by doc columns id int)",
        "select * from xmltable(not true passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(1 and 2 as n), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(not true as n), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces(1 is null as n), '/x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc columns id int path 1 and 2)",
        "select * from xmltable('/x' passing doc columns id int path not true)",
        "select * from xmltable('/x' passing doc columns id int path 1 is null)",
        "select * from xmltable('/x' passing doc columns id int path 1 in (1, 2))",
        "select * from xmltable(xmlnamespaces(), '/x' passing doc columns id int)",
        "select * from xmltable(xmlnamespaces('x' as ns,), '/x' passing doc columns id int)",
        "select * from xmltable('/x' passing doc columns)",
        "select * from xmltable('/x' passing doc columns id int,)",
        "select * from xmltable('/x' passing doc columns id int default 1 and 2)",
        "select * from xmltable('/x' passing doc columns id int path 'x' path 'y')",
        "select * from xmltable('/x' passing doc columns id int default 1 default 2)",
        "select * from xmltable('/x' passing doc columns id int null not null)",
        "select * from xmltable('/x' passing doc columns id int foo 1)",
        "select * from xmltable('/x' passing doc columns id int __pg__is_not_null true)",
        "select * from xmltable('/x' passing doc columns 'id' int)",
        "select * from xmltable('/x' passing doc columns select int)",
        "select * from json_table(doc, '$' as select columns (id int))",
        "select * from json_table(doc, '$' columns (select int))",
        "select * from json_table(doc, '$' columns (nested path '$' as select columns (id int)))",
        "select * from items window",
        "select 1 window select as ()",
        "select * from items window w (partition by id)",
        "select * from items window w as (partition id)",
        "select * from items window w as (partition by)",
        "select * from items window w as (order by)",
        "select * from items window w as (rows unbounded following)",
        "select * from items window w as (rows between current row and 1 preceding)",
        "select * from items for nonsense",
        "select * from items for no update",
        "select * from items for update of",
        "select * from items for update skip",
        "select * from items for update for read only",
        "select * from items for share for read only",
        "select * from (update items set value = 1) changed",
        "select (insert into items values (1))",
        "select 1 in (delete from items)",
        "select json_array(update items set value = 1)",
        "select unique (select 1)",
        "select * from graph_table(g match (p is person |) columns (p.id))",
        "select * from graph_table(g match ((p)-(q) columns (p.id))",
        "select * from graph_table(g match (p){1,} columns (p.id))",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn malformed_alter_table_commands_are_rejected_without_token_skipping() {
    for sql in [
        "alter table t add column",
        "alter table t add column c",
        "alter table t drop column",
        "alter table t alter column c",
        "alter table t alter column c set default",
        "alter table t alter column c set not",
        "alter table t alter column c set statistics nonsense",
        "alter table t alter column 0 set statistics 10",
        "alter table t alter column c reset ()",
        "alter table t validate constraint",
        "alter table t replica identity using index",
        "alter table t attach partition child",
        "alter table t detach partition child concurrently finalize",
        "alter table t split partition child into ()",
        "alter table t merge partitions () into child",
        "alter table t enable trigger",
        "alter table t set access method",
        "alter table t set tablespace",
        "alter table t set (fillfactor 80)",
        "alter table t reset (fillfactor 80)",
        "alter table t alter column c set (n_distinct 10)",
        "alter table t set logged garbage",
        "alter table t add column c int,",
        "alter table t add constraint",
        "alter table t add constraint c check ()",
        "alter table t alter constraint",
        "alter table t alter constraint c",
        "alter table t alter constraint c not valid",
        "alter table t alter column id add identity",
        "alter table t alter column id add generated as identity",
        "alter table t alter column id add generated always as identity ()",
        "alter table t alter column id set generated",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn malformed_create_table_elements_are_rejected() {
    for sql in [
        "create table t (id)",
        "create table t (id int,)",
        "create table t (id int default)",
        "create table t (id int constraint named)",
        "create table t (id int collate)",
        "create table t (id int generated by default as (id + 1))",
        "create table t (id int generated always as identity ())",
        "create table t (id int generated by default as identity ())",
        "create table t (id int references)",
        "create table t (id int references parent())",
        "create table t (id int references parent(id) on delete)",
        "create table t (constraint c check ())",
        "create table t (unique ())",
        "create table t (primary (id))",
        "create table t (foreign key () references parent(id))",
        "create table t (foreign key (id) references)",
        "create table t (foreign key (id) references parent(id) match partial)",
        "create table t (check (id > 0) deferrable)",
        "create table t (not null id enforced)",
        "create table t (unique (id) not valid)",
        "create table t (unique nulls distinct using index idx)",
        "create table t (unique nulls not distinct using index idx)",
        "create table t (unique (lower(id)))",
        "create table t (primary key (t.id))",
        "create table t (primary key (id) no inherit)",
        "create table t (exclude (id with =) not enforced)",
        "create table t (foreign key (id) references parent(id) no inherit)",
        "create table t (foreign key (period valid_at) references parent(id))",
        "create table t (foreign key (id, period valid_at, other) references parent(id))",
        "create table t (id int references parent(id, period valid_at))",
        "create table t (unique (id) deferrable not deferrable)",
        "create table t (unique (id) not deferrable initially deferred)",
        "create table t (check (id > 0) enforced not enforced)",
        "create table t (check (id > 0) nonsense)",
        "create table t (exclude ())",
        "create table t (exclude (id with))",
        "create table t (id int) partition by range (id collate)",
        "create table t (id int) partition by range (id desc)",
        "create table t (id int) partition by range (id nulls first)",
        "create table t (id int) partition by range (id int4_ops (option = true))",
        "create table t (id int) partition by range (id,)",
        "create table t (id int) partition by range (id + 1)",
        "create table t (id int) partition by range (t.id)",
        "create table t (id int) partition by range (lower(id) over ())",
        "create table t (id int) partition by range (id::bigint)",
        "create table t (id int, exclude (id + 1 with =))",
        "create table t (id int, exclude (t.id with =))",
        "create table t (id int, exclude (lower(id) over () with =))",
        "create table t (id int, exclude (id with plus))",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn malformed_type_names_are_rejected_without_dropping_tokens() {
    for sql in [
        "create table t (value int garbage)",
        "create table t (value app..custom_type)",
        "create table t (value int(3))",
        "create table t (value numeric())",
        "create table t (value numeric(10,))",
        "create table t (value float(0))",
        "create table t (value float(54))",
        "create table t (value float(10, 20))",
        "create table t (value timestamp with zone)",
        "create table t (value int[foo])",
        "create table t (value int[-1])",
        "create table t (value int array[2][3])",
        "create table t (value interval year to day)",
        "create table t (value interval(1, 2))",
        "create table t (value setof)",
        "create function f(value app..custom_type) returns int language sql as 'select 1'",
        "create function f(value int garbage) returns int language sql as 'select 1'",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn malformed_object_name_and_signature_lists_are_rejected() {
    for sql in [
        "drop table app.",
        "drop table app.items nonsense",
        "drop table app.items,",
        "drop role alice,",
        "drop owned alice",
        "drop owned by",
        "drop function f(int",
        "drop function f(int,)",
        "drop function f(value int default 1)",
        "drop function f(int) garbage",
        "drop function +(int, int)",
        "drop aggregate agg",
        "drop aggregate agg()",
        "drop aggregate +(int)",
        "drop function 'f'()",
        "drop function 123()",
        "drop operator +",
        "drop operator +(integer)",
        "drop operator +(none, none)",
        "drop operator plus(int, int)",
        "drop function schema..f(int)",
        "alter function f(int,) stable",
        "alter operator +(int,) set (restrict = join)",
        "alter operator + set (restrict = join)",
        "alter operator + set schema app",
        "alter operator + owner to alice",
        "alter operator plus(int, int) set (restrict = join)",
        "alter extension e add operator +",
        "alter extension e add operator plus(int, int)",
        "alter extension e add aggregate agg",
        "grant select on table app.items, to alice",
        "grant select on table app.items nonsense to alice",
        "grant execute on function f(int,) to alice",
        "grant execute on function +(int, int) to alice",
        "grant select on all tables in schema to alice",
        "reassign owned by alice, to bob",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn malformed_comment_and_security_label_identities_are_rejected() {
    for sql in [
        "comment on table app. is 'x'",
        "comment on table select is 'x'",
        "comment on table app.* is 'x'",
        "comment on database app.db is 'x'",
        "comment on function f(int,) is 'x'",
        "comment on aggregate agg is 'x'",
        "comment on aggregate agg() is 'x'",
        "comment on operator + is 'x'",
        "comment on operator plus(int, int) is 'x'",
        "comment on cast int as text is 'x'",
        "comment on cast (int text) is 'x'",
        "comment on constraint c app.t is 'x'",
        "comment on constraint c on is 'x'",
        "comment on trigger tr app.t is 'x'",
        "comment on operator class app.ops is 'x'",
        "comment on operator class app.* using btree is 'x'",
        "comment on operator family app, ops using btree is 'x'",
        "comment on transform for app.t plpgsql is 'x'",
        "security label on function f(int,) is 'x'",
        "security label on operator +(int, int) is 'x'",
        "security label on constraint c on app.t is 'x'",
        "security label on policy p on app.t is 'x'",
        "security label on rule r on app.t is 'x'",
        "security label on trigger tr on app.t is 'x'",
        "security label on operator family app.ops using btree is 'x'",
        "security label on operator class app.ops using btree is 'x'",
        "security label on cast (int as text) is 'x'",
        "security label on transform for app.t language sql is 'x'",
        "security label for on table t is 'x'",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn incomplete_with_and_dml_forms_are_rejected() {
    for sql in [
        "with x select 1",
        "with x as select 1",
        "with x() as (select 1) select * from x",
        "with x(id,) as (select 1) select * from x",
        "with x as (select 1), select * from x",
        "with x as (select 1) create table t (id int)",
        "with x as (create table t (id int)) select 1",
        "with select as (select 1) select 1",
        "with x(select) as (select 1) select 1",
        "with recursive x(id) as (values (1)) search first by id set ord select * from x",
        "with recursive x(id) as (values (1)) search depth by id set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by id, set ord select * from x",
        "with recursive x(id) as (values (1)) search depth first by id set select * from x",
        "with recursive x(id) as (values (1)) cycle set mark using path select * from x",
        "with recursive x(id) as (values (1)) cycle id, set mark using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark to 'Y' using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark default 'N' using path select * from x",
        "with recursive x(id) as (values (1)) cycle id set mark using select * from x",
        "with outer_cte as (select 1) (with inner_cte as (select 2) select * from inner_cte)",
        "insert t values (1)",
        "insert into t",
        "insert into t alias values (1)",
        "insert into t as values (1)",
        "insert into t (payload.) values (1)",
        "insert into t (select) values (1)",
        "insert into t (nums[]) values (1)",
        "insert into t (id) default values",
        "insert into t overriding user value default values",
        "insert into t (id) overriding system value default values",
        "insert into t with x as (select 1) update source set id = 1",
        "insert into t with x as (select 1) delete from source",
        "insert into t with x as (select 1) merge into target using source on true when matched then do nothing",
        "insert into t values (1) on conflict () do nothing",
        "insert into t values (1) on conflict (id,) do nothing",
        "insert into t values (1) on conflict on constraint do nothing",
        "insert into t values (1) on conflict (id) where do nothing",
        "insert into t values (1) on conflict do update set",
        "insert into t values (1) returning",
        "insert into t values (1) returning with () id",
        "insert into t values (1) returning with (old as previous,) id",
        "insert into t values (1) returning with (old previous) id",
        "insert into t values (1) on conflict do select for",
        "insert into t values (1) on conflict do select for update of t",
        "insert into t values (1) on conflict do select skip locked",
        "insert into t values (1) on conflict do select where",
        "update t",
        "update t set",
        "update t alias(id) set id = 1",
        "update t set payload. = 1",
        "update t set select = 1",
        "update t set nums[] = 1",
        "update t set nums[1 = 1",
        "update t set (a., b) = row(1, 2)",
        "update t set id = 1 from",
        "update t set id = 1 where current of",
        "update t set id = 1 where current item_cursor",
        "update t for portion of valid_time set id = 1",
        "update t for portion of valid_time () set id = 1",
        "update t for portion of valid_time from start to set id = 1",
        "delete t",
        "delete from",
        "delete from t using",
        "delete from t where current of",
        "delete from t for portion of valid_time (requested_period",
        "merge into t using s on true",
        "merge into t using s on true when matched then insert values (1)",
        "merge into t using s on true when not matched by source then insert values (1)",
        "merge into t using s on true when not matched then update set id = 1",
        "merge into t using s on true when not matched by target then delete",
        "merge into t using s on true when matched then update set",
        "merge into t using s on true when not matched then insert values ()",
        "merge into t using s on true when not matched then insert (id) default values",
        "merge into t using s on true when not matched then insert overriding user value default values",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn top_level_statements_require_semicolon_separators() {
    let error = pg_parser::parse("checkpoint checkpoint")
        .expect_err("adjacent statements without a semicolon must be rejected");
    assert!(!error.message.is_empty());
}

#[test]
fn malformed_privilege_name_categories_are_rejected() {
    for sql in [
        "grant from on table items to alice",
        "grant select(select) on table items to alice",
        "grant select(app.id) on table items to alice",
        "grant all privileges (app.id) on table items to alice",
        "grant alter system(work_mem) on parameter work_mem to admin",
        "revoke select option for app_reader from alice",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}

#[test]
fn incomplete_create_alter_drop_and_utility_forms_are_rejected() {
    for sql in [
        "create database",
        "create database select",
        "create database app select = 'value'",
        "create database app owner select",
        "create database app encoding current_user",
        "create foreign data wrapper select",
        "create schema select",
        "create domain select as integer",
        "create type select as enum ('x')",
        "create function select() returns integer language sql as 'select 1'",
        "create function authorization.fn() returns integer language sql as 'select 1'",
        "create extension select",
        "create publication select for all tables",
        "create publication p for tables in schema select",
        "create subscription select connection 'x' publication p",
        "create policy select on t",
        "create trigger select before insert on t execute function f()",
        "create event trigger select on ddl_command_start execute function f()",
        "create event trigger e on ddl_command_start when select in ('x') execute function f()",
        "create server select foreign data wrapper fdw",
        "create user mapping for current_user server select",
        "create tablespace select location '/tmp'",
        "create access method select type table handler app.handler",
        "create access method am type table handler select",
        "create table if t (id int)",
        "create table if not t (id int)",
        "create table 'items' (id int)",
        "create table select (id int)",
        "create table catalog.schema.items.extra (id int)",
        "create table t (select int)",
        "create table t (id boolean default 1 and 2)",
        "create table t (id boolean default not true)",
        "create table t (id boolean default 1 is null)",
        "create table t (id boolean default 1 in (1, 2))",
        "create table child (id int references parent(id) on delete cascade on delete restrict)",
        "create table child (id int references parent(id) on update cascade on update restrict)",
        "create table t of",
        "create table t of app.item_type (name text)",
        "create table t of app.item_type ()",
        "create table t of app.item_type (like other_table)",
        "create table t of app.item_type[]",
        "create table p partition of parent for values in ()",
        "create table p partition of parent for values from () to (1)",
        "create table p partition of parent for values from (1) to ()",
        "create table p partition of parent for values with (modulus 4, modulus 8, remainder 1)",
        "create table p partition of parent for values with (modulus 4, remainder 1, remainder 2)",
        "create local table t (id int)",
        "create temp database appdb",
        "create temp materialized view mv as select 1",
        "create unlogged index idx on t (id)",
        "create or table t (id int)",
        "create or replace table t (id int)",
        "create table t () as select 1",
        "create table t () inherits ()",
        "create table t () inherits (parent,)",
        "create table t (id int) as select 1",
        "create table t using as select 1",
        "create table t with () as select 1",
        "create table t on commit rows as select 1",
        "create table t tablespace as select 1",
        "create table t",
        "create table t with (fillfactor = 80)",
        "create table t (id int) with (fillfactor 80)",
        "create table t (id int) with ()",
        "create table copied with (fillfactor 80) as select 1",
        "create materialized view mv with (fillfactor 80) as select 1",
        "create materialized view mv with () as select 1",
        "create view v with (security_barrier true) as select 1",
        "create index idx on t (id) with (fillfactor 80)",
        "create index idx on t (id int4_ops (foo bar))",
        "create table t (id int, unique (id) with (fillfactor 80))",
        "create table t (id int, exclude using gist (id with =) with (fillfactor 80))",
        "create table t as update source set value = 1",
        "create table t as execute p()",
        "create table t as execute p with nonsense data",
        "create materialized view mv as execute p",
        "create index if idx on t (id)",
        "create index select on t (id)",
        "create index idx on t (collate c)",
        "create index idx on t (id collate)",
        "create index idx on t (id nulls)",
        "create index idx on t (id asc desc)",
        "create index idx on t (id nulls first asc)",
        "create index idx on t (id text_ops ())",
        "create index idx on t (id + 1)",
        "create index idx on t (t.id)",
        "create index idx on t (lower(id) over ())",
        "create index idx on t (id::bigint)",
        "create schema",
        "create schema if not exists app create table items (id integer)",
        "create schema app create database nested_db",
        "create schema app create table copied as select 1",
        "create schema app create foreign table remote (id int) server srv",
        "create schema app create materialized view mv as select 1",
        "create schema app grant app_reader to alice",
        "create schema app grant app_reader to alice with admin option",
        "create view v(select) as select 1",
        "create table t (id int constraint select check (id > 0))",
        "create table t using select (id int)",
        "create operator family app.family using select",
        "create operator class app.ops for type int using btree as operator 1 plus",
        "create operator class app.ops for type int using btree as operator 1 plus(int, int)",
        "create operator class app.ops for type int using btree as function 1 app.compare(int, int) for search",
        "create operator class app.ops for type int using btree as function 1 app.compare(int, int) for order by app.family",
        "create rule select as on select to t do nothing",
        "alter database select refresh collation version",
        "alter database app set tablespace select",
        "alter tablespace select set (seq_page_cost = 1)",
        "alter policy select on t using (true)",
        "alter event trigger select enable",
        "alter foreign data wrapper select no handler",
        "alter server select version '1'",
        "alter publication select set (publish = 'insert')",
        "alter subscription select enable",
        "alter table t rename column select to value",
        "alter table t drop column select",
        "alter table t enable trigger select",
        "alter table t set tablespace select",
        "alter table t replica identity using index select",
        "alter type app.composite rename attribute select to value",
        "drop database select",
        "drop tablespace select",
        "drop subscription select",
        "savepoint select",
        "prepare select as select 1",
        "execute select",
        "deallocate select",
        "listen select",
        "notify select",
        "unlisten select",
        "reindex schema select",
        "import foreign schema select from server s into local_schema",
        "import foreign schema remote from server select into local_schema",
        "declare select cursor for select 1",
        "set select to 'value'",
        "create function f() returns",
        "create function f() returns table",
        "create function f() returns table () language sql as 'select 1'",
        "create function f() returns table (id)",
        "create function f() returns table (id integer,)",
        "create function f(value integer,) returns integer",
        "create function f() returns table (select integer) language sql as 'select 1'",
        "create function f(select integer) returns integer language sql as 'select 1'",
        "create function f(in select integer) returns integer language sql as 'select 1'",
        "create function f(select out integer) returns integer language sql as 'select 1'",
        "create function f(out value integer) returns table (result integer)",
        "create procedure p() returns table (result integer)",
        "create function f() called null input",
        "create function f() returns null input",
        "create function f() external security",
        "create function f() not strict",
        "create function f() transform type integer",
        "create function f() transform for integer",
        "create function f() transform for type",
        "create function f() support",
        "create function f() cost a + 1",
        "create function f() as 'body', 'link', 'extra'",
        "create function f() begin atomic return 1 end",
        "create function f() begin atomic return 1;",
        "create function f(value app.source%) returns integer",
        "create function f() returns setof %type",
        "create function f() set time",
        "create function f() set time zone interval '1' second language sql as 'select 1'",
        "create function f() set schema app",
        "create function f() set session default",
        "create function f() set xml option",
        "create function f() set transaction snapshot",
        "create function f() reset transaction level",
        "create function f() reset session",
        "create function f() set catalog 'other_db'",
        "create view v",
        "create recursive view v as select 1",
        "create recursive view v(id) as select 1 with check option",
        "create view v as select 1 with local option",
        "create view v as select 1 with cascaded check",
        "create index idx on t garbage",
        "alter table",
        "alter table if t owner to alice",
        "alter table t nonsense",
        "alter sequence",
        "alter sequence s nonsense",
        "alter database",
        "alter database d refresh version",
        "alter database d refresh collation",
        "alter database d refresh collation version garbage",
        "alter database d set tablespace",
        "alter system nonsense",
        "alter system set work_mem",
        "alter tablespace ts nonsense",
        "alter tablespace ts set ()",
        "alter role",
        "alter role all superuser",
        "alter group g user r",
        "alter type mood add value happy",
        "alter type mood rename value 'sad' 'happy'",
        "alter statistics st",
        "alter statistics st set statistics nonsense",
        "alter statistics st set statistics 1.5",
        "create statistics if not exists on category from items",
        "create statistics stats on from items",
        "create statistics stats on category, from items",
        "create statistics stats on price * quantity from items",
        "create statistics stats on items.category from items",
        "create statistics stats on lower(category) over () from items",
        "create statistics stats on 1::int from items",
        "create table hash_part partition of hash_parent for values with (\"MODULUS\" 4, remainder 0)",
        "alter event trigger et",
        "alter event trigger et enable nonsense",
        "alter foreign data wrapper",
        "alter foreign data fdw options (host 'x')",
        "alter foreign data wrapper fdw nonsense",
        "alter foreign data wrapper fdw options (host db)",
        "alter server s",
        "alter server s version current_user",
        "alter subscription",
        "alter subscription s",
        "alter subscription s connection current_user",
        "alter subscription s set publication",
        "alter subscription s set publication p,",
        "alter subscription s add publication p,",
        "alter subscription s drop publication p,",
        "alter subscription s refresh nonsense",
        "create subscription s connection 'x' publication p with (enabled true)",
        "create subscription s connection 'x' publication p,",
        "create subscription s connection 'x' publication p with (pg.enabled = true)",
        "create subscription s connection 'x' publication p with (enabled =)",
        "alter subscription s set (enabled true)",
        "alter subscription s refresh sequences with (copy_data = true)",
        "alter subscription s enable with (copy_data = true)",
        "alter user mapping garbage",
        "alter user mapping for u server s",
        "alter user mapping for u server s options (host db)",
        "alter domain",
        "alter domain d set default",
        "alter domain d set nonsense",
        "alter domain d add check value > 0",
        "alter domain d drop constraint",
        "alter type t set ()",
        "alter type t set (input =)",
        "alter collation c refresh",
        "alter policy p t",
        "alter policy p on t using true",
        "alter policy p on t to using (true)",
        "create property graph",
        "create property graph g vertex tables ()",
        "create property graph g edge tables (e source v)",
        "create graph g",
        "create property graph g edge tables (e source v destination v) vertex tables (v)",
        "create property graph g vertex tables (v) vertex tables (w)",
        "create property graph g edge tables (e source v destination v) edge tables (f source v destination v)",
        "alter property graph",
        "alter property graph g add nonsense",
        "alter property graph g drop vertex tables ()",
        "alter property graph g alter vertex table v add label l",
        "alter property graph g alter vertex table v alter label l add no properties",
        "alter property graph g alter vertex table v alter label l add properties all columns",
        "alter property graph g alter vertex table v alter label l add properties ()",
        "alter property graph g alter vertex table v alter label l add properties (id,)",
        "alter type composite add attribute c",
        "alter type composite drop attribute",
        "alter type composite alter attribute c type",
        "alter type composite alter attribute c set type int",
        "alter type composite add attribute c int not null",
        "alter type composite add attribute c int,",
        "alter extension",
        "alter extension e nonsense",
        "alter extension e update to",
        "alter extension e add function",
        "alter extension e add cast (int text)",
        "alter extension e add operator class opc btree",
        "alter extension e add policy p",
        "alter extension e add trigger t",
        "alter extension e add rule r",
        "alter operator family opf using btree",
        "alter operator family opf using btree add",
        "alter operator family opf using btree add operator 1 plus",
        "alter operator family opf using btree add operator 1 plus(int, int)",
        "alter operator family opf using btree drop operator 1 ()",
        "alter function f()",
        "alter function stable",
        "alter function f() security",
        "alter function f() cost",
        "alter function f() set work_mem",
        "alter operator +(int, int)",
        "alter operator +(int, int) set ()",
        "alter operator +(int, int) set (restrict app.f)",
        "alter operator +(int, int) set (restrict =)",
        "alter operator +(int, int) set (restrict = app.f garbage)",
        "alter text search dictionary",
        "alter text search dictionary d ()",
        "alter text search configuration c add mapping word with simple",
        "alter text search configuration c add mapping for with simple",
        "alter text search configuration c alter mapping replace simple",
        "alter text search configuration c drop mapping for",
        "alter table t rename to",
        "alter table t rename column to c",
        "alter domain d rename constraint c d2",
        "alter aggregate agg rename to agg2",
        "alter function if exists f() rename to g",
        "alter operator class opc rename to opc2",
        "alter function f() depends extension e",
        "alter function f() depends on extension",
        "alter table t depends on extension e",
        "alter index if exists i depends on extension e",
        "alter function f() set schema",
        "alter database d set schema s",
        "alter function if exists f() set schema s",
        "alter schema s owner role",
        "alter schema s owner to",
        "alter table t owner to",
        "alter extension e rename to e2",
        "alter access method heap rename to heap2",
        "alter operator +(int, int) rename to plus",
        "alter property graph if exists g rename to g2",
        "drop nonsense",
        "drop table",
        "drop table if t",
        "drop foreign fdw",
        "drop foreign data fdw",
        "drop trigger tr",
        "drop rule r",
        "drop policy p",
        "drop schema app.other",
        "drop event ddl_event",
        "drop text search parser",
        "drop materialized mv",
        "drop database",
        "drop database app with",
        "drop database app ()",
        "drop database app with ()",
        "drop database app (force,)",
        "drop database app (verbose)",
        "drop database app force",
        "alter database app",
        "alter database app with",
        "drop role",
        "drop cast garbage",
        "drop cast (int text)",
        "drop cast (int as)",
        "drop transform for int sql",
        "drop transform for language sql",
        "drop operator class opc btree",
        "drop operator family using btree",
        "drop tablespace",
        "drop tablespace ts cascade",
        "drop subscription",
        "drop subscription s garbage",
        "drop user mapping for u",
        "drop user mapping server s",
        "drop concurrently index i",
        "show",
        "show time",
        "show transaction isolation",
        "show work_mem garbage",
        "show app.",
        "start",
        "start transaction read",
        "start transaction read only,",
        "begin isolation nonsense",
        "begin read only,",
        "commit and",
        "rollback to",
        "savepoint",
        "release savepoint",
        "prepare transaction",
        "commit prepared gid",
        "rollback prepared gid",
        "prepare",
        "prepare p () as select 1",
        "prepare p (int,) as select 1",
        "prepare p (int) select 1",
        "prepare p as vacuum",
        "execute",
        "execute p()",
        "execute p(1,)",
        "execute p(1",
        "execute p garbage",
        "deallocate",
        "deallocate prepare",
        "deallocate all garbage",
        "explain",
        "explain vacuum t",
        "explain grant select on table t to alice",
        "explain checkpoint",
        "explain verbose analyze select 1",
        "explain () select 1",
        "explain call f()",
        "explain analyze analyze select 1",
        "explain verbose verbose select 1",
        "explain (analyze true) analyze select 1",
        "explain (analyze = true) select 1",
        "checkpoint (public.flush)",
        "vacuum (verbose true garbage) t",
        "vacuum (verbose = true) t",
        "vacuum app.items(app.id)",
        "analyze app.items(id,)",
        "analyze (select) t",
        "call",
        "call f",
        "call f(1) filter (where true)",
        "call f(1) over ()",
        "call f(1) within group (order by 1)",
        "call f(1) ignore nulls",
        "call f(1) respect nulls",
        "call f(1)::int",
        "do",
        "do language",
        "do select",
        "copy t nonsense",
        "copy t to stdout with ()",
        "copy t to stdout with (format = csv)",
        "copy t to stdout with (format app.csv)",
        "copy t to stdout with (reject_limit 1 + 2)",
        "copy t to stdout with (force_not_null ())",
        "copy t to stdout with (force_not_null (id, 2))",
        "copy t to stdout with (force_not_null (id,))",
        "copy t to stdout using '|'",
        "copy t to stdout delimiters",
        "copy (select 1) to stdout delimiters '|'",
        "copy t to stdout encoding as 'UTF8'",
        "copy t to stdout force quote",
        "copy t to stdout force not id",
        "copy (select 1) from stdout",
        "copy binary (select 1) to stdout",
        "set constraints deferred",
        "set constraints app.c, deferred",
        "set constraints app.c extra immediate",
        "set constraints all, app.c immediate",
        "set constraints app.c deferred immediate",
        "set app. to value",
        "reset app.",
        "do",
        "return value + 1",
        "copy (vacuum t) to stdout",
        "copy t to stdout where id > 0",
        "vacuum t (",
        "vacuum verbose full t",
        "vacuum full full t",
        "vacuum analyze verbose t",
        "vacuum t,",
        "analyze full t",
        "analyze freeze t",
        "analyze analyze t",
        "analyze t,",
        "checkpoint garbage",
        "discard garbage",
        "lock table",
        "lock table app.items alias",
        "lock table app.items,",
        "lock app.items in access mode",
        "lock app.items in row mode",
        "lock app.items in share update mode",
        "lock app.items in share row mode",
        "lock app.items in exclusive",
        "lock app.items in share exclusive mode",
        "lock app.items nowait in share mode",
        "lock only ()",
        "lock (app.items)",
        "lock app.items in share mode nowait garbage",
        "listen",
        "unlisten",
        "unlisten * garbage",
        "notify",
        "notify channel, 1",
        "notify channel,",
        "load extension.so",
        "load",
        "refresh materialized view",
        "refresh materialized concurrently view mv",
        "refresh materialized view mv concurrently",
        "refresh materialized view mv no data",
        "reindex nonsense",
        "reindex index",
        "reindex table",
        "reindex schema",
        "reindex schema app.extra",
        "reindex concurrently table app.items",
        "reindex table app.items concurrently",
        "reindex (verbose = true) table app.items",
        "reindex (public.verbose) table app.items",
        "reindex (verbose true garbage) table app.items",
        "reindex (select) table app.items",
        "truncate",
        "truncate table app.items alias",
        "truncate app.items,",
        "truncate app.items identity restart",
        "truncate app.items cascade restart identity",
        "repack using",
        "repack (verbose = true) app.items",
        "repack using index item_idx",
        "cluster using item_idx",
        "cluster (verbose true) verbose",
        "cluster (verbose true) verbose app.items",
        "cluster only app.items",
        "cluster app.items(id)",
        "cluster item_idx on",
        "reassign owned by old_owner",
        "comment on table items",
        "security label on table items is 1",
        "import foreign schema remote",
        "import foreign schema remote limit (items) from server srv into public",
        "import foreign schema remote limit to () from server srv into public",
        "import foreign schema remote limit to (items,) from server srv into public",
        "import foreign schema remote except to (items) from server srv into public",
        "import foreign schema remote limit to (items alias) from server srv into public",
        "import foreign schema remote from server srv into public options ()",
        "return",
        "wait for '0/0'",
        "wait for lsn 1",
        "wait for lsn '0/0' with ()",
        "wait for lsn '0/0' with (timeout 1,)",
        "wait for lsn '0/0' with (timeout = 1)",
        "set time zone 1 + 2",
        "set time zone interval '1' day",
        "set names UTF8",
        "set names 65001",
        "set catalog 'other_database'",
        "set role default",
        "set role 1",
        "set role select",
        "set session authorization 1",
        "set session authorization select",
        "set work_mem to 1 + 2",
        "alter system set work_mem = 1 + 2",
        "alter database d set local work_mem to '4MB'",
        "alter role r set session work_mem to '4MB'",
        "begin work transaction",
        "begin read only,",
        "end transaction work",
        "commit work transaction",
        "rollback transaction work",
        "abort work transaction",
        "declare c cursor select 1",
        "declare c cursor for with x as (select 1) update source set id = 1",
        "declare c cursor for with x as (select 1) delete from source",
        "declare c cursor for with x as (select 1) merge into target using source on true when matched then do nothing",
        "close",
        "fetch",
        "fetch absolute from c",
        "fetch relative in c",
        "fetch forward + c",
        "fetch backward all 1 c",
        "fetch first 1 c",
        "move all",
        "create role",
        "create role r with nonsense",
        "create role r no inherit",
        "create role r in alice",
        "create role r in role",
        "create role r admin role alice",
        "create role r role group alice",
        "create role r sysid -1",
        "create role r connection limit 1.5",
        "alter role r connection limit 1.5",
        "create role r \"SUPERUSER\"",
        "alter role r \"LOGIN\"",
        "alter default privileges for alice grant select on tables to bob",
        "alter default privileges for role user alice grant select on tables to bob",
        "alter default privileges",
        "alter default privileges garbage grant select on tables to bob",
        "alter default privileges in app grant select on tables to bob",
        "alter default privileges in schema app.audit grant select on tables to bob",
        "alter default privileges grant select on table t to bob",
        "alter default privileges grant select on databases to bob",
        "alter default privileges grant select on tables to bob granted by owner",
        "create role 'alice'",
        "create role 1.5",
        "create role +",
        "create role select",
        "create role public",
        "create role current_user",
        "create role none",
        "alter role 'alice' login",
        "alter type mood drop value 'sad'",
        "drop role 'alice'",
        "grant select on table t to 'alice'",
        "grant role app_reader to alice",
        "revoke role app_reader from alice",
        "grant app_reader to group alice",
        "grant select on table t to alice cascade",
        "grant select on table t to alice restrict",
        "grant app_reader to alice cascade",
        "grant app_reader to alice restrict",
        "grant select, on table t to alice",
        "revoke select, on table t from alice",
        "grant app_reader, to alice",
        "grant all to alice",
        "grant all privileges to alice",
        "revoke all from alice",
        "alter default privileges grant select, on tables to alice",
        "grant usage on large objects 1 to alice",
        "grant usage on parameter app..work_mem to alice",
        "grant usage on table catalog.schema.table.extra to alice",
        "grant connect on database app.db to alice",
        "alter role alice rename to public",
        "alter table app.items alias rename to renamed_items",
        "alter foreign table app.items alias rename to renamed_items",
        "alter sequence only app.seq set schema archive",
        "alter extension if exists ext set schema archive",
        "alter schema if exists app owner to owner_role",
        "create sequence",
        "create sequence s cache",
        "create sequence s as int[]",
        "create sequence s as setof int",
        "alter sequence s",
        "create schema",
        "create schema authorization",
        "create schema app authorization",
        "create schema if not exists app create table t (id int)",
        "create schema app create database nested",
        "create schema app revoke select on table t from public",
        "create domain d",
        "create type",
        "create type mood as enum ('ok',)",
        "create type composite_type as (value int not null)",
        "create type shell (input textin)",
        "create type r as range (subtype int)",
        "create operator === (function app.eq_int)",
        "create text search dictionary d (template simple)",
        "alter text search dictionary d (stopwords english)",
        "create type r as range ()",
        "create extension",
        "create extension ext version 1",
        "create extension ext version select",
        "create language plpgsql handler",
        "create language 'plpgsql'",
        "create procedural trusted language plpgsql",
        "create language plpgsql handler app.h no",
        "create language plpgsql handler app.h validator",
        "create subscription s publication p",
        "create server s foreign wrapper fdw",
        "create user mapping for u",
        "create tablespace ts location 1",
        "create tablespace ts location '/tmp' with ()",
        "create tablespace ts location '/tmp' with (random_page_cost 1.1)",
        "create tablespace ts location '/tmp' with (random_page_cost =)",
        "alter tablespace ts set (random_page_cost 1.1)",
        "create access method am type invalid handler h",
        "create foreign data wrapper",
        "create foreign data wrapper fdw handler",
        "create foreign data wrapper fdw options (host 1)",
        "create foreign data wrapper fdw options (host = 'db')",
        "create foreign table ft (id int) using heap server srv",
        "create foreign table ft (id int) with (fillfactor = 80) server srv",
        "create foreign table ft (id int) on commit drop server srv",
        "create foreign table ft (id int) tablespace fast server srv",
        "create foreign table ft (id int) partition by range (id) server srv",
        "create foreign table ft (id int) server srv options (host 1)",
        "create server srv foreign data wrapper fdw options (host 1)",
        "create user mapping for u server srv options (user current_user)",
        "import foreign schema remote from server srv into public options (key 1)",
        "create cast (int as text)",
        "create cast (int text) without function",
        "create cast (int as text) with function +(int)",
        "create conversion conv for 'UTF8' to 'LATIN1'",
        "create transform for int language sql ()",
        "create transform for int language sql (from sql with function +(int))",
        "create transform for int language sql (from sql with function app.from_sql(int),)",
        "create transform for int language sql (from sql with function app.from_sql(int), from sql with function app.other(int))",
        "create transform for int language sql (to sql with function app.to_sql(int), to sql with function app.other(int))",
        "create operator class opc for type int using btree",
        "create operator family opf",
        "create rule r on update to t do nothing",
        "create rule r as on nonsense to t do nothing",
        "create rule r as on update to t do vacuum t",
        "create rule r as on update to t do call f()",
        "create rule r as on update to t do (notify ch; create table x (id int))",
        "create assertion a check (1 = 1)",
        "create aggregate agg(int)",
        "create aggregate agg(out value int) (sfunc = f, stype = int)",
        "create aggregate agg(value int default 1) (sfunc = f, stype = int)",
        "create aggregate agg(int,) (sfunc = f, stype = int)",
        "create aggregate agg(order by) (sfunc = f, stype = int)",
        "create aggregate agg(variadic values int[] order by variadic ordered text[]) (sfunc = f, stype = int)",
        "create aggregate agg(variadic values int[] order by variadic first int[], variadic second int[]) (sfunc = f, stype = int)",
        "create aggregate agg (sfunc app.f)",
        "create aggregate agg (select = app.f)",
        "create aggregate agg (sfunc =)",
        "create aggregate agg (sfunc = app.f garbage)",
        "create aggregate agg (sfunc = app.f,)",
        "create operator +",
        "create operator === (leftarg = int garbage, rightarg = int, function = app.eq_int)",
        "create operator === (leftarg = int, rightarg = int, function = app..eq_int)",
        "create operator === (leftarg = int, rightarg = int, commutator = app.)",
        "create operator === (leftarg = int, rightarg = int, commutator = app.===)",
        "create collation c",
        "create text search configuration c",
        "create policy p t",
        "create policy p on t as invalid",
        "create policy p on t as \"PERMISSIVE\"",
        "create trigger tr update on t execute function f()",
        "create trigger tr before update of on t execute function f()",
        "create trigger tr after insert on t referencing for each row execute function f()",
        "create trigger tr after insert on t execute function f(1 + 2)",
        "create constraint trigger tr after insert on t execute function f()",
        "create constraint trigger tr after insert on t deferrable not deferrable for each row execute function f()",
        "create constraint trigger tr after insert on t initially deferred not deferrable for each row execute function f()",
        "create constraint trigger tr after insert on t initially immediate initially deferred for each row execute function f()",
        "create constraint trigger tr after insert on t not enforced for each row execute function f()",
        "create constraint trigger tr after insert on t no inherit for each row execute function f()",
        "create constraint trigger tr after insert on t not valid for each row execute function f()",
        "create event trigger et on ddl_command_start execute function f(1)",
        "create event trigger et on ddl_command_start when tag in () execute function f()",
        "create event trigger et on ddl_command_start when tag in ('x',) execute function f()",
        "create event trigger et on ddl_command_start when tag in ('x') and execute function f()",
        "create materialized view mv",
        "create materialized view mv as",
        "create materialized view mv as update t set value = 1",
    ] {
        let error = parse_error(sql);
        assert!(!error.message.is_empty(), "{sql:?} returned an empty error");
    }
}
